# Generated by Django 3.2.9 on 2021-11-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_key',
        ),
    ]
