# Generated by Django 3.2.9 on 2021-11-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='namehi',
        ),
        migrations.AddField(
            model_name='user',
            name='user_access',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
