# Generated by Django 3.2.9 on 2021-11-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211111_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_access',
            field=models.IntegerField(default=4),
        ),
    ]
