# Generated by Django 3.2.9 on 2021-11-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211113_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='Users',
        ),
    ]
